baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Today I Learned'

[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
