style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/michenriksen/hugo-theme-til
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
  commit_groups:
    sort_by: Custom
    title_maps:
      feat: Features
      fix: Fixes
      docs: Documentation
    title_order:
      - feat
      - fix
      - docs
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
